### ISSUE TITLE
Wrong CSS url

### ISSUE THREAD

**Issue by Quadrubo** [yepsua/filament-range-field#10]
The css is not loading when embedding the range slider. The `Request URL` seems to be wrong. 
Shouldn't it be 
`vendor/yepsua/filament-range-field/css/filament-forms-range-component.min.css`
instead of
`vendor/filament-range-field/css/filament-forms-range-component.min.css`?

If this behaviour is wrong and not just my problem I'll gladly submit a Pull request :)

```
Request URL: http://localhost/vendor/filament-range-field/css/filament-forms-range-component.min.css
Request Method: GET
Status Code: 404 Not Found
```

**Comment by oyepez003** [comment]
The URL is the correct 

When you run the command to publish the assets you should see something like this:

```shell
php artisan vendor:publish --tag="filament-range-field-assets"
```
**Copied Directory [/vendor/yepsua/filament-range-field/resources/dist] To [/public/vendor/filament-range-field]
Publishing complete.**

So the **/vendor/filament-range-field/css/filament-forms-range-component.min.css** is the correct URL.

Regards.
