### ISSUE TITLE
How to get current slide value

### ISSUE THREAD

**Issue by barovski** [yepsua/filament-range-field#13]
This is not a bug, because I have a 30 options I will  hide the values below slider, but how to get current slide value when slider move?

Thanks

**Comment by oyepez003** [comment]
You can use the reactive or lazy method if you need to do something in the form when the field value changes.

```php
RangeSlider::make('range')
    ...
    ->reactive()
    ->afterStateUpdated(function (Closure $set, $state) {
      // Do anything you need
    })
    ...
```

**Comment by barovski** [comment]
Thanks, I want to show it in range-slider.blade.php, I'm not so familiar with livewire

**Comment by oyepez003** [comment]
If you want to rewrite the template you can do it by publishing the templates and updating the file by yourself:

```sh
php artisan vendor:publish --tag="filament-range-field-views"
```
