### ISSUE TITLE
How to set current step

### ISSUE THREAD

**Issue by barovski** [yepsua/filament-range-field#8]
I need to set current step for example 3 of 10, it always stay on 5 - middle of range slider

**Comment by oyepez003** [comment]
You can do it like any other filament field using the default method: https://filamentphp.com/docs/2.x/forms/fields#setting-a-default-value


```php
...
RangeSlider::make("modelField")
  ->min(1)
  ->max(10)
  ->default(3)
...
```

Regards.

**Comment by barovski** [comment]
@oyepez003 sorry for disturb you again , but I don't have modelField it come from loop.  I need to put default data somehow.
...
RangeSlider::make("modelField")
  ->min(1)
  ->max(10)
  ->default(3)
...

**Comment by oyepez003** [comment]
I don't understand what **I don't have modelField it come from loop** means, provide some code to get your point...
